### ISSUE TITLE
NodeMCU epd driver

### ISSUE THREAD

**Issue by pastukhov** [FrankBuss/wifi-epaper#1]
Is there epd NodeMCU driver available?

**Comment by FrankBuss** [comment]
Yes, for the old 2.7" display see here:
https://hackaday.io/project/20466-wifi-epaper/log/57324-first-working-prototype
and for the new 4.2" display see here:
https://hackaday.io/project/20466-wifi-epaper/log/59098-testing-the-new-42-black-white-red-epaper-display
But still very much prototype state. Follow my project on hackaday for updates.

**Comment by pastukhov** [comment]
Here is my version with lua and u8g driver [https://github.com/pastukhov/oled-wemos](https://github.com/pastukhov/oled-wemos)
